// web/app/(auth)/auth/page.tsx
"use client";

// /auth — sign-in / sign-up / LDAP entry page (single page, mode toggle).

import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { useApp } from "@/lib/store";
import { errorMessage } from "@/lib/api";
import { Spinner } from "@/components/ui/Spinner";

type Mode = "signin" | "signup" | "ldap";

const APP_NAME = "JyotiGPT";

export default function AuthPage() {
  const { user, config, loading, signIn, signUp } = useApp();
  const router = useRouter();

  const [loaded, setLoaded] = useState(false);
  const [mode, setMode] = useState<Mode>("signin");
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [ldapUsername, setLdapUsername] = useState("");
  const [submitting, setSubmitting] = useState(false);

  // Redirect if a session already exists (e.g. after refresh or trusted-header
  // auth). Run after config loads so LDAP mode is known.
  useEffect(() => {
    if (!loading) {
      setLoaded(true);
      if (config?.auth.enable_ldap) {
        setMode("ldap");
      }
      if (user) {
        router.replace("/");
      }
    }
  }, [loading, config, user, router]);

  const submitHandler = useCallback(
    async (event: React.FormEvent) => {
      event.preventDefault();
      if (submitting) return;
      setSubmitting(true);
      try {
        if (mode === "ldap") {
          await signIn(ldapUsername, password, true);
        } else if (mode === "signin") {
          await signIn(email, password);
        } else {
          await signUp(name, email, password);
        }
        toast.success("You're now logged in.");
        router.replace("/");
      } catch (error) {
        toast.error(errorMessage(error));
      } finally {
        setSubmitting(false);
      }
    },
    [submitting, mode, signIn, signUp, ldapUsername, password, email, name, router],
  );

  return (
    <div className="w-full h-screen max-h-[100dvh] text-white relative">
      <div className="w-full h-full absolute top-0 left-0 bg-white dark:bg-black"></div>

      <div className="w-full absolute top-0 left-0 right-0 h-8" />

      {loaded && (
        <>
          <div className="fixed m-10 z-50">
            <div className="flex space-x-2">
              <div className="self-center">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  crossOrigin="anonymous"
                  src="/favicon.png"
                  className="w-6 rounded-full"
                  alt="logo"
                />
              </div>
            </div>
          </div>

          <div className="fixed bg-transparent min-h-screen w-full flex justify-center font-primary z-50 text-black dark:text-white">
            <div className="w-full sm:max-w-md px-10 min-h-screen flex flex-col text-center">
              <div className="my-auto pb-10 w-full dark:text-gray-100">
                <form
                  className="flex flex-col justify-center"
                  onSubmit={submitHandler}
                >
                  <div className="mb-1">
                    <div className="text-2xl font-medium">
                      {mode === "ldap"
                        ? `Sign in to ${APP_NAME} with LDAP`
                        : mode === "signin"
                          ? `Sign in to ${APP_NAME}`
                          : `Sign up to ${APP_NAME}`}
                    </div>
                  </div>

                  <div className="flex flex-col mt-4">
                      {mode === "signup" && (
                        <div className="mb-2">
                          <div className="text-sm font-medium text-left mb-1">
                            Name
                          </div>
                          <input
                            value={name}
                            onChange={(e) => setName(e.target.value)}
                            type="text"
                            className="my-0.5 w-full text-sm outline-none bg-transparent"
                            autoComplete="name"
                            placeholder="Enter Your Full Name"
                            required
                          />
                        </div>
                      )}

                      {mode === "ldap" ? (
                        <div className="mb-2">
                          <div className="text-sm font-medium text-left mb-1">
                            Username
                          </div>
                          <input
                            value={ldapUsername}
                            onChange={(e) => setLdapUsername(e.target.value)}
                            type="text"
                            className="my-0.5 w-full text-sm outline-none bg-transparent"
                            autoComplete="username"
                            name="username"
                            placeholder="Enter Your Username"
                            required
                          />
                        </div>
                      ) : (
                        <div className="mb-2">
                          <div className="text-sm font-medium text-left mb-1">
                            Email
                          </div>
                          <input
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            type="email"
                            className="my-0.5 w-full text-sm outline-none bg-transparent"
                            autoComplete="email"
                            name="email"
                            placeholder="Enter Your Email"
                            required
                          />
                        </div>
                      )}

                      <div>
                        <div className="text-sm font-medium text-left mb-1">
                          Password
                        </div>
                        <input
                          value={password}
                          onChange={(e) => setPassword(e.target.value)}
                          type="password"
                          className="my-0.5 w-full text-sm outline-none bg-transparent"
                          placeholder="Enter Your Password"
                          autoComplete="current-password"
                          name="current-password"
                          required
                        />
                      </div>
                  </div>

                  <div className="mt-5">
                    {mode === "ldap" ? (
                      <button
                        type="submit"
                        disabled={submitting}
                        className="bg-gray-700/5 hover:bg-gray-700/10 dark:bg-gray-100/5 dark:hover:bg-gray-100/10 dark:text-gray-300 dark:hover:text-white transition w-full rounded-full font-medium text-sm py-2.5 disabled:opacity-50"
                      >
                        Authenticate
                      </button>
                    ) : (
                      <>
                        <button
                          type="submit"
                          disabled={submitting}
                          className="bg-gray-700/5 hover:bg-gray-700/10 dark:bg-gray-100/5 dark:hover:bg-gray-100/10 dark:text-gray-300 dark:hover:text-white transition w-full rounded-full font-medium text-sm py-2.5 disabled:opacity-50"
                        >
                          {submitting ? (
                            <span className="flex justify-center">
                              <Spinner className="size-4" />
                            </span>
                          ) : mode === "signin" ? (
                            "Sign in"
                          ) : (
                            "Create Account"
                          )}
                        </button>

                        {config?.auth.enable_signup && (
                          <div className="mt-4 text-sm text-center">
                            {mode === "signin"
                              ? "Don't have an account?"
                              : "Already have an account?"}
                            <button
                              className="font-medium underline"
                              type="button"
                              onClick={() =>
                                setMode(mode === "signin" ? "signup" : "signin")
                              }
                            >
                              {mode === "signin" ? "Sign up" : "Sign in"}
                            </button>
                          </div>
                        )}
                      </>
                    )}
                  </div>
                </form>

                {config?.auth.enable_ldap && (
                  <div className="mt-2">
                    <button
                      className="flex justify-center items-center text-xs w-full text-center underline"
                      type="button"
                      onClick={() =>
                        setMode(mode === "ldap" ? "signin" : "ldap")
                      }
                    >
                      <span>
                        {mode === "ldap"
                          ? "Continue with Email"
                          : "Continue with LDAP"}
                      </span>
                    </button>
                  </div>
                )}
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}

// src/app/auth/+page.svelte
<script>
	import { toast } from 'svelte-sonner';

	import { onMount, getContext, tick } from 'svelte';
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';

	import { getBackendConfig } from '$api';
	import { ldapUserSignIn, getSessionUser, userSignIn, userSignUp } from '$api/auths';

	import { JYOTIGPT_API_BASE_URL, JYOTIGPT_BASE_URL } from '$shared/constants';
	import { JYOTIGPT_NAME, config, user, socket } from '$shared/stores';

	import { generateInitialsImage, canvasPixelTest } from '$shared/utils';

	import Spinner from '$shared/components/Spinner.svelte';
	import OnBoarding from '$features/app/OnBoarding.svelte';

	const i18n = getContext('i18n');

	let loaded = false;

	let mode = $config?.features.enable_ldap ? 'ldap' : 'signin';

	let name = '';
	let email = '';
	let password = '';

	let ldapUsername = '';

	const querystringValue = (key) => {
		const querystring = window.location.search;
		const urlParams = new URLSearchParams(querystring);
		return urlParams.get(key);
	};

	const setSessionUser = async (sessionUser) => {
		if (sessionUser) {
			console.log(sessionUser);
			toast.success($i18n.t(`You're now logged in.`));
			if (sessionUser.token) {
				localStorage.token = sessionUser.token;
			}

			$socket.emit('user-join', { auth: { token: sessionUser.token } });
			await user.set(sessionUser);
			await config.set(await getBackendConfig());

			const redirectPath = querystringValue('redirect') || '/';
			goto(redirectPath);
		}
	};

	const signInHandler = async () => {
		const sessionUser = await userSignIn(email, password).catch((error) => {
			toast.error(`${error}`);
			return null;
		});

		await setSessionUser(sessionUser);
	};

	const signUpHandler = async () => {
		const sessionUser = await userSignUp(name, email, password, generateInitialsImage(name)).catch(
			(error) => {
				toast.error(`${error}`);
				return null;
			}
		);

		await setSessionUser(sessionUser);
	};

	const ldapSignInHandler = async () => {
		const sessionUser = await ldapUserSignIn(ldapUsername, password).catch((error) => {
			toast.error(`${error}`);
			return null;
		});
		await setSessionUser(sessionUser);
	};

	const submitHandler = async () => {
		if (mode === 'ldap') {
			await ldapSignInHandler();
		} else if (mode === 'signin') {
			await signInHandler();
		} else {
			await signUpHandler();
		}
	};

	const checkOauthCallback = async () => {
		if (!$page.url.hash) {
			return;
		}
		const hash = $page.url.hash.substring(1);
		if (!hash) {
			return;
		}
		const params = new URLSearchParams(hash);
		const token = params.get('token');
		if (!token) {
			return;
		}
		const sessionUser = await getSessionUser(token).catch((error) => {
			toast.error(`${error}`);
			return null;
		});
		if (!sessionUser) {
			return;
		}
		localStorage.token = token;
		await setSessionUser(sessionUser);
	};

	let onboarding = false;

	async function setLogoImage() {
		await tick();
		const logo = document.getElementById('logo');

		if (logo) {
			const isDarkMode = document.documentElement.classList.contains('dark');

			if (isDarkMode) {
				const darkImage = new Image();
				darkImage.src = '/static/favicon-dark.png';

				darkImage.onload = () => {
					logo.src = '/static/favicon-dark.png';
					logo.style.filter = ''; // Ensure no inversion is applied if favicon-dark.png exists
				};

				darkImage.onerror = () => {
					logo.style.filter = 'invert(1)'; // Invert image if favicon-dark.png is missing
				};
			}
		}
	}

	onMount(async () => {
		if ($user !== undefined) {
			const redirectPath = querystringValue('redirect') || '/';
			goto(redirectPath);
		}
		await checkOauthCallback();

		loaded = true;
		setLogoImage();

		if (($config?.features.auth_trusted_header ?? false) || $config?.features.auth === false) {
			await signInHandler();
		} else {
			onboarding = $config?.onboarding ?? false;
		}
	});
</script>

<svelte:head>
	<title>
		{`${$JYOTIGPT_NAME}`}
	</title>
</svelte:head>

<OnBoarding
	bind:show={onboarding}
	getStartedHandler={() => {
		onboarding = false;
		mode = $config?.features.enable_ldap ? 'ldap' : 'signup';
	}}
/>

<div class="w-full h-screen max-h-[100dvh] text-white relative">
	<div class="w-full h-full absolute top-0 left-0 bg-white dark:bg-black"></div>

	<div class="w-full absolute top-0 left-0 right-0 h-8 drag-region" />

	{#if loaded}
		<div class="fixed m-10 z-50">
			<div class="flex space-x-2">
				<div class=" self-center">
					<img
						id="logo"
						crossorigin="anonymous"
						src="{JYOTIGPT_BASE_URL}/static/splash.png"
						class=" w-6 rounded-full"
						alt="logo"
					/>
				</div>
			</div>
		</div>

		<div
			class="fixed bg-transparent min-h-screen w-full flex justify-center font-primary z-50 text-black dark:text-white"
		>
			<div class="w-full sm:max-w-md px-10 min-h-screen flex flex-col text-center">
				{#if ($config?.features.auth_trusted_header ?? false) || $config?.features.auth === false}
					<div class=" my-auto pb-10 w-full">
						<div
							class="flex items-center justify-center gap-3 text-xl sm:text-2xl text-center font-semibold dark:text-gray-200"
						>
							<div>
								{$i18n.t('Signing in to {{JYOTIGPT_NAME}}', { JYOTIGPT_NAME: $JYOTIGPT_NAME })}
							</div>

							<div>
								<Spinner />
							</div>
						</div>
					</div>
				{:else}
					<div class="  my-auto pb-10 w-full dark:text-gray-100">
						<form
							class=" flex flex-col justify-center"
							on:submit={(e) => {
								e.preventDefault();
								submitHandler();
							}}
						>
							<div class="mb-1">
								<div class=" text-2xl font-medium">
									{#if $config?.onboarding ?? false}
										{$i18n.t(`Get started with {{JYOTIGPT_NAME}}`, { JYOTIGPT_NAME: $JYOTIGPT_NAME })}
									{:else if mode === 'ldap'}
										{$i18n.t(`Sign in to {{JYOTIGPT_NAME}} with LDAP`, { JYOTIGPT_NAME: $JYOTIGPT_NAME })}
									{:else if mode === 'signin'}
										{$i18n.t(`Sign in to {{JYOTIGPT_NAME}}`, { JYOTIGPT_NAME: $JYOTIGPT_NAME })}
									{:else}
										{$i18n.t(`Sign up to {{JYOTIGPT_NAME}}`, { JYOTIGPT_NAME: $JYOTIGPT_NAME })}
									{/if}
								</div>

								{#if $config?.onboarding ?? false}
									<div class=" mt-1 text-xs font-medium text-gray-500">
										ⓘ {$JYOTIGPT_NAME}
										{$i18n.t(
											'does not make any external connections, and your data stays securely on your locally hosted server.'
										)}
									</div>
								{/if}
							</div>

							{#if $config?.features.enable_login_form || $config?.features.enable_ldap}
								<div class="flex flex-col mt-4">
									{#if mode === 'signup'}
										<div class="mb-2">
											<div class=" text-sm font-medium text-left mb-1">{$i18n.t('Name')}</div>
											<input
												bind:value={name}
												type="text"
												class="my-0.5 w-full text-sm outline-hidden bg-transparent"
												autocomplete="name"
												placeholder={$i18n.t('Enter Your Full Name')}
												required
											/>
										</div>
									{/if}

									{#if mode === 'ldap'}
										<div class="mb-2">
											<div class=" text-sm font-medium text-left mb-1">{$i18n.t('Username')}</div>
											<input
												bind:value={ldapUsername}
												type="text"
												class="my-0.5 w-full text-sm outline-hidden bg-transparent"
												autocomplete="username"
												name="username"
												placeholder={$i18n.t('Enter Your Username')}
												required
											/>
										</div>
									{:else}
										<div class="mb-2">
											<div class=" text-sm font-medium text-left mb-1">{$i18n.t('Email')}</div>
											<input
												bind:value={email}
												type="email"
												class="my-0.5 w-full text-sm outline-hidden bg-transparent"
												autocomplete="email"
												name="email"
												placeholder={$i18n.t('Enter Your Email')}
												required
											/>
										</div>
									{/if}

									<div>
										<div class=" text-sm font-medium text-left mb-1">{$i18n.t('Password')}</div>

										<input
											bind:value={password}
											type="password"
											class="my-0.5 w-full text-sm outline-hidden bg-transparent"
											placeholder={$i18n.t('Enter Your Password')}
											autocomplete="current-password"
											name="current-password"
											required
										/>
									</div>
								</div>
							{/if}
							<div class="mt-5">
								{#if $config?.features.enable_login_form || $config?.features.enable_ldap}
									{#if mode === 'ldap'}
										<button
											class="bg-gray-700/5 hover:bg-gray-700/10 dark:bg-gray-100/5 dark:hover:bg-gray-100/10 dark:text-gray-300 dark:hover:text-white transition w-full rounded-full font-medium text-sm py-2.5"
											type="submit"
										>
											{$i18n.t('Authenticate')}
										</button>
									{:else}
										<button
											class="bg-gray-700/5 hover:bg-gray-700/10 dark:bg-gray-100/5 dark:hover:bg-gray-100/10 dark:text-gray-300 dark:hover:text-white transition w-full rounded-full font-medium text-sm py-2.5"
											type="submit"
										>
											{mode === 'signin'
												? $i18n.t('Sign in')
												: ($config?.onboarding ?? false)
													? $i18n.t('Create Admin Account')
													: $i18n.t('Create Account')}
										</button>

										{#if $config?.features.enable_signup && !($config?.onboarding ?? false)}
											<div class=" mt-4 text-sm text-center">
												{mode === 'signin'
													? $i18n.t("Don't have an account?")
													: $i18n.t('Already have an account?')}

												<button
													class=" font-medium underline"
													type="button"
													on:click={() => {
														if (mode === 'signin') {
															mode = 'signup';
														} else {
															mode = 'signin';
														}
													}}
												>
													{mode === 'signin' ? $i18n.t('Sign up') : $i18n.t('Sign in')}
												</button>
											</div>
										{/if}
									{/if}
								{/if}
							</div>
						</form>

						{#if Object.keys($config?.oauth?.providers ?? {}).length > 0}
							<div class="inline-flex items-center justify-center w-full">
								<hr class="w-32 h-px my-4 border-0 dark:bg-gray-100/10 bg-gray-700/10" />
								{#if $config?.features.enable_login_form || $config?.features.enable_ldap}
									<span
										class="px-3 text-sm font-medium text-gray-900 dark:text-white bg-transparent"
										>{$i18n.t('or')}</span
									>
								{/if}

								<hr class="w-32 h-px my-4 border-0 dark:bg-gray-100/10 bg-gray-700/10" />
							</div>
							<div class="flex flex-col space-y-2">
								{#if $config?.oauth?.providers?.google}
									<button
										class="flex justify-center items-center bg-gray-700/5 hover:bg-gray-700/10 dark:bg-gray-100/5 dark:hover:bg-gray-100/10 dark:text-gray-300 dark:hover:text-white transition w-full rounded-full font-medium text-sm py-2.5"
										on:click={() => {
											window.location.href = `${JYOTIGPT_BASE_URL}/oauth/google/login`;
										}}
									>
										<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" class="size-6 mr-3">
											<path
												fill="#EA4335"
												d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"
											/><path
												fill="#4285F4"
												d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"
											/><path
												fill="#FBBC05"
												d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"
											/><path
												fill="#34A853"
												d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"
											/><path fill="none" d="M0 0h48v48H0z" />
										</svg>
										<span>{$i18n.t('Continue with {{provider}}', { provider: 'Google' })}</span>
									</button>
								{/if}
								{#if $config?.oauth?.providers?.microsoft}
									<button
										class="flex justify-center items-center bg-gray-700/5 hover:bg-gray-700/10 dark:bg-gray-100/5 dark:hover:bg-gray-100/10 dark:text-gray-300 dark:hover:text-white transition w-full rounded-full font-medium text-sm py-2.5"
										on:click={() => {
											window.location.href = `${JYOTIGPT_BASE_URL}/oauth/microsoft/login`;
										}}
									>
										<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 21 21" class="size-6 mr-3">
											<rect x="1" y="1" width="9" height="9" fill="#f25022" /><rect
												x="1"
												y="11"
												width="9"
												height="9"
												fill="#00a4ef"
											/><rect x="11" y="1" width="9" height="9" fill="#7fba00" /><rect
												x="11"
												y="11"
												width="9"
												height="9"
												fill="#ffb900"
											/>
										</svg>
										<span>{$i18n.t('Continue with {{provider}}', { provider: 'Microsoft' })}</span>
									</button>
								{/if}
								{#if $config?.oauth?.providers?.github}
									<button
										class="flex justify-center items-center bg-gray-700/5 hover:bg-gray-700/10 dark:bg-gray-100/5 dark:hover:bg-gray-100/10 dark:text-gray-300 dark:hover:text-white transition w-full rounded-full font-medium text-sm py-2.5"
										on:click={() => {
											window.location.href = `${JYOTIGPT_BASE_URL}/oauth/github/login`;
										}}
									>
										<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" class="size-6 mr-3">
											<path
												fill="currentColor"
												d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.92 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57C20.565 21.795 24 17.31 24 12c0-6.63-5.37-12-12-12z"
											/>
										</svg>
										<span>{$i18n.t('Continue with {{provider}}', { provider: 'GitHub' })}</span>
									</button>
								{/if}
								{#if $config?.oauth?.providers?.oidc}
									<button
										class="flex justify-center items-center bg-gray-700/5 hover:bg-gray-700/10 dark:bg-gray-100/5 dark:hover:bg-gray-100/10 dark:text-gray-300 dark:hover:text-white transition w-full rounded-full font-medium text-sm py-2.5"
										on:click={() => {
											window.location.href = `${JYOTIGPT_BASE_URL}/oauth/oidc/login`;
										}}
									>
										<svg
											xmlns="http://www.w3.org/2000/svg"
											fill="none"
											viewBox="0 0 24 24"
											stroke-width="1.5"
											stroke="currentColor"
											class="size-6 mr-3"
										>
											<path
												stroke-linecap="round"
												stroke-linejoin="round"
												d="M15.75 5.25a3 3 0 0 1 3 3m3 0a6 6 0 0 1-7.029 5.912c-.563-.097-1.159.026-1.563.43L10.5 17.25H8.25v2.25H6v2.25H2.25v-2.818c0-.597.237-1.17.659-1.591l6.499-6.499c.404-.404.527-1 .43-1.563A6 6 0 1 1 21.75 8.25Z"
											/>
										</svg>

										<span
											>{$i18n.t('Continue with {{provider}}', {
												provider: $config?.oauth?.providers?.oidc ?? 'SSO'
											})}</span
										>
									</button>
								{/if}
							</div>
						{/if}

						{#if $config?.features.enable_ldap && $config?.features.enable_login_form}
							<div class="mt-2">
								<button
									class="flex justify-center items-center text-xs w-full text-center underline"
									type="button"
									on:click={() => {
										if (mode === 'ldap')
											mode = ($config?.onboarding ?? false) ? 'signup' : 'signin';
										else mode = 'ldap';
									}}
								>
									<span
										>{mode === 'ldap'
											? $i18n.t('Continue with Email')
											: $i18n.t('Continue with LDAP')}</span
									>
								</button>
							</div>
						{/if}
					</div>
				{/if}
			</div>
		</div>
	{/if}
</div>
